api: ignore deprecations for the node and baseUrl TS errors
Gotta fix then eventually:

8.025 tsconfig.json(5,25): error TS5107: Option 'moduleResolution=node10' is deprecated and will stop functioning in TypeScript 7.0. Specify compilerOption '"ignoreDeprecations": "6.0"' to silence this error.
8.025 Visit https://aka.ms/ts6 for migration information.
8.025 tsconfig.json(10,5): error TS5101: Option 'baseUrl' is deprecated and will stop functioning in TypeScript 7.0. Specify compilerOption '"ignoreDeprecations": "6.0"' to silence this error.
8.025 Visit https://aka.ms/ts6 for migration information.