api: relax compiler options to ignore any & bump lib to fix Object.hasOwn issue
Coming from: src/utils/emotions.ts(17,32): error TS7006: Parameter
'emotion' implicitly has an 'any' type.

By the way, I think it's safe to get back and fix all of this validators
and middleware since we're using zod now